INSERT INTO USER (NAME, EMAIL, CELLPHONE, SPASSWORD, SUPERUSER)
VALUES ('Daniel Rodrigues', 'daniel@gmail.com', '1123123212', 'teste123', 1);

INSERT INTO USER (NAME, EMAIL, CELLPHONE, SPASSWORD, SUPERUSER)
VALUES ('Adilio Silva', 'adilio@gmail.com', '119823782', 'teste123', 0);

INSERT INTO USER (NAME, EMAIL, CELLPHONE, SPASSWORD, SUPERUSER)
VALUES ('Pedro Pedraum', 'pedro@gmail.com', '211111213', 'teste123', 1);

INSERT INTO USER (NAME, EMAIL, CELLPHONE, SPASSWORD, SUPERUSER)
VALUES ('Maxwell Praga', 'max@gmail.com', '2111123132', 'teste123', 0);

INSERT INTO SCHEDULE (SCHEDULE_DATE, TYPE_SERVICE, ID_USER) 
VALUES ('2019-12-31 17:30:00', 'Agendou um corte de cabelo simples', 4);

INSERT INTO SCHEDULE (SCHEDULE_DATE, TYPE_SERVICE, ID_USER) 
VALUES ('2020-01-15 19:30:00', 'Agendou uma compra de roupas', 4);

INSERT INTO SCHEDULE (SCHEDULE_DATE, TYPE_SERVICE, ID_USER) 
VALUES ('2019-12-31 13:30:00', 'Agendou uma compra de roupas', 1);

INSERT INTO SCHEDULE (SCHEDULE_DATE, TYPE_SERVICE, ID_USER) 
VALUES ('2020-01-01 17:30:00', 'Agendou um corte de cabelo simples', 2);
 
SELECT * FROM 
	`USER` U,
	`SCHEDULE` S
WHERE
	U.ID_USER = S.ID_USER
